[cursor]
style = "Block"

[env]
TERM = "alacritty"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "PageUp"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "PageDown"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mods = "Shift"

[scrolling]
history = 99999

[shell]
args = ["-c", "neofetch && exec bash --login"]
program = "/bin/bash"

[window]
opacity = 0.9
