#!/bin/sh

BAR_NAME=$1

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    BAR_MONITOR=$m polybar --reload $BAR_NAME &
  done
else
  polybar --reload $BAR_NAME &
fi

