#! /bin/sh

# https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux

systemctl stop docker.service
systemctl stop docker.socket
sed -i 's/ExecStart=\/usr\/bin\/dockerd -H fd:\/\//ExecStart=\/usr\/bin\/dockerd -g \/home\/marm\/\.local\/docker -H fd:\/\//g' /lib/systemd/system/docker.service
rm -rf /var/lib/docker
systemctl daemon-reload
systemctl start docker

