#!/usr/bin/env bash

VOLUME=$(pamixer --get-volume)

if [ "$1" == "toggle" ]; then
  if [ $VOLUME -lt 1 ]; then
    VOLUME=100
  else
    VOLUME=0
  fi
else
  SIGN=${1:0:1}
  STEP=${1:1}

  [ "$SIGN" == "+" ] && VOLUME=$(( VOLUME + STEP ))
  [ "$SIGN" == "-" ] && VOLUME=$(( VOLUME - STEP ))
  [ $VOLUME -gt 100 ] && VOLUME=100
  [ $VOLUME -lt 0  ] && VOLUME=0
fi

pactl set-sink-volume @DEFAULT_SINK@ ${VOLUME}%
