#!/bin/sh

REPO_PATH=$(pwd)

link_file() {
  [ -d $HOME/$1 ] && rm -rf $HOME/$1
  ln -sf $REPO_PATH/$1 $HOME/$1
}

# home
[ -f $HOME/.bash_profile ] && mv $HOME/.bash_profile $HOME/.bash_profile.backup
link_file ".aliases"
link_file ".bash_completion"
link_file ".bashrc"
link_file ".profile"
link_file ".xinitrc"
link_file ".Xresources"

touch "$HOME/.workrc"

# .local
[ ! -d $HOME/.local ] && mkdir $HOME/.local

link_file ".local/usrbin"

