#!/usr/bin/env sh

case $BLOCK_BUTTON in
  1) pgrep -x dunst >/dev/null && notify-send --icon=none "Disk space" "$(df -h --output=target,used,size)" ;;
esac

echo  " $(df -h "$1" | awk ' /[0-9]/ {print $3 "/" $2}')"
