#!/usr/bin/env sh

case $BLOCK_BUTTON in
	1) volume -5 ;;
	3) volume +5 ;;
	2) volume toggle ;;
esac

VOLUME=$(pamixer --get-volume)
if [ "$VOLUME" -gt "70" ]; then
	ICON=""
elif [ "$VOLUME" -lt "1" ]; then
	ICON=""
elif [ "$VOLUME" -lt "30" ]; then
	ICON=""
else
	ICON=""
fi

echo "$ICON $VOLUME%"

